/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfidentialERC20,
  IConfidentialERC20Interface,
} from "../../contracts/IConfidentialERC20";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "isOperatorApproved",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "euint64",
        name: "amount",
        type: "bytes32",
      },
    ],
    name: "operatorTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConfidentialERC20__factory {
  static readonly abi = _abi;
  static createInterface(): IConfidentialERC20Interface {
    return new Interface(_abi) as IConfidentialERC20Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConfidentialERC20 {
    return new Contract(address, _abi, runner) as unknown as IConfidentialERC20;
  }
}
