/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConfidentialPayroll__factory } from "./ConfidentialPayroll__factory";
export { ConfidentialPayrollFactory__factory } from "./ConfidentialPayrollFactory__factory";
