/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialPayrollFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "allPayrolls" | "create" | "totalPayrolls" | "userPayroll"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PayrollCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allPayrolls",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "create", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalPayrolls",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userPayroll",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allPayrolls",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPayrolls",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPayroll",
    data: BytesLike
  ): Result;
}

export namespace PayrollCreatedEvent {
  export type InputTuple = [employer: AddressLike, payroll: AddressLike];
  export type OutputTuple = [employer: string, payroll: string];
  export interface OutputObject {
    employer: string;
    payroll: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialPayrollFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialPayrollFactory;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialPayrollFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allPayrolls: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  create: TypedContractMethod<[], [string], "nonpayable">;

  totalPayrolls: TypedContractMethod<[], [bigint], "view">;

  userPayroll: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allPayrolls"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "create"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPayrolls"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userPayroll"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "PayrollCreated"
  ): TypedContractEvent<
    PayrollCreatedEvent.InputTuple,
    PayrollCreatedEvent.OutputTuple,
    PayrollCreatedEvent.OutputObject
  >;

  filters: {
    "PayrollCreated(address,address)": TypedContractEvent<
      PayrollCreatedEvent.InputTuple,
      PayrollCreatedEvent.OutputTuple,
      PayrollCreatedEvent.OutputObject
    >;
    PayrollCreated: TypedContractEvent<
      PayrollCreatedEvent.InputTuple,
      PayrollCreatedEvent.OutputTuple,
      PayrollCreatedEvent.OutputObject
    >;
  };
}
