/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialERC20WrapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveOperator"
      | "balanceOf"
      | "confidentialProtocolId"
      | "decimals"
      | "finalizeUnwrap"
      | "isOperatorApproved"
      | "name"
      | "operatorTransfer"
      | "requestUnwrap"
      | "symbol"
      | "transfer"
      | "underlying"
      | "unwrapRequests"
      | "wrap"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PublicDecryptionVerified"
      | "Transfer"
      | "UnwrapFinalized"
      | "UnwrapRequested"
      | "Wrap"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeUnwrap",
    values: [BytesLike, BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperatorApproved",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "operatorTransfer",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUnwrap",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "underlying",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unwrapRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "wrap", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "approveOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeUnwrap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperatorApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operatorTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUnwrap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "underlying", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unwrapRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wrap", data: BytesLike): Result;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnwrapFinalizedEvent {
  export type InputTuple = [
    receiver: AddressLike,
    requestId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    receiver: string,
    requestId: string,
    amount: bigint
  ];
  export interface OutputObject {
    receiver: string;
    requestId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnwrapRequestedEvent {
  export type InputTuple = [
    receiver: AddressLike,
    requestId: BytesLike,
    encHandle: BytesLike
  ];
  export type OutputTuple = [
    receiver: string,
    requestId: string,
    encHandle: string
  ];
  export interface OutputObject {
    receiver: string;
    requestId: string;
    encHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WrapEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialERC20Wrapper extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialERC20Wrapper;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialERC20WrapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveOperator: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  finalizeUnwrap: TypedContractMethod<
    [
      requestId: BytesLike,
      handles: BytesLike[],
      abiEncodedCleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  isOperatorApproved: TypedContractMethod<
    [operator: AddressLike, owner: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  operatorTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;

  requestUnwrap: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encAmount: BytesLike,
      inputProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, encAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  underlying: TypedContractMethod<[], [string], "view">;

  unwrapRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, boolean] & {
        receiver: string;
        encHandle: string;
        finalized: boolean;
      }
    ],
    "view"
  >;

  wrap: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveOperator"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeUnwrap"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      handles: BytesLike[],
      abiEncodedCleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isOperatorApproved"
  ): TypedContractMethod<
    [operator: AddressLike, owner: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "operatorTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUnwrap"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encAmount: BytesLike,
      inputProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, encAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "underlying"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unwrapRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, boolean] & {
        receiver: string;
        encHandle: string;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "wrap"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "UnwrapFinalized"
  ): TypedContractEvent<
    UnwrapFinalizedEvent.InputTuple,
    UnwrapFinalizedEvent.OutputTuple,
    UnwrapFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "UnwrapRequested"
  ): TypedContractEvent<
    UnwrapRequestedEvent.InputTuple,
    UnwrapRequestedEvent.OutputTuple,
    UnwrapRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Wrap"
  ): TypedContractEvent<
    WrapEvent.InputTuple,
    WrapEvent.OutputTuple,
    WrapEvent.OutputObject
  >;

  filters: {
    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;

    "Transfer(address,address)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "UnwrapFinalized(address,bytes32,uint64)": TypedContractEvent<
      UnwrapFinalizedEvent.InputTuple,
      UnwrapFinalizedEvent.OutputTuple,
      UnwrapFinalizedEvent.OutputObject
    >;
    UnwrapFinalized: TypedContractEvent<
      UnwrapFinalizedEvent.InputTuple,
      UnwrapFinalizedEvent.OutputTuple,
      UnwrapFinalizedEvent.OutputObject
    >;

    "UnwrapRequested(address,bytes32,bytes32)": TypedContractEvent<
      UnwrapRequestedEvent.InputTuple,
      UnwrapRequestedEvent.OutputTuple,
      UnwrapRequestedEvent.OutputObject
    >;
    UnwrapRequested: TypedContractEvent<
      UnwrapRequestedEvent.InputTuple,
      UnwrapRequestedEvent.OutputTuple,
      UnwrapRequestedEvent.OutputObject
    >;

    "Wrap(address,uint256)": TypedContractEvent<
      WrapEvent.InputTuple,
      WrapEvent.OutputTuple,
      WrapEvent.OutputObject
    >;
    Wrap: TypedContractEvent<
      WrapEvent.InputTuple,
      WrapEvent.OutputTuple,
      WrapEvent.OutputObject
    >;
  };
}
