/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialPayrollInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEmployee"
      | "confidentialProtocolId"
      | "employer"
      | "fundPayroll"
      | "getEmployeeInfo"
      | "getEmployeeList"
      | "getEmployeeSalary"
      | "getMySalary"
      | "getMyTotalPaid"
      | "payAll"
      | "paySalary"
      | "removeEmployee"
      | "updateSalary"
      | "withdrawSurplus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmployeeAdded"
      | "EmployeeRemoved"
      | "PayrollFunded"
      | "PayrollWithdrawn"
      | "SalaryPaid"
      | "SalaryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "employer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundPayroll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployeeSalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMySalary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyTotalPaid",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "payAll", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paySalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSalary",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSurplus",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployeeSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMySalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyTotalPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paySalary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSurplus",
    data: BytesLike
  ): Result;
}

export namespace EmployeeAddedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeRemovedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollWithdrawnEvent {
  export type InputTuple = [employer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [employer: string, amount: bigint];
  export interface OutputObject {
    employer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryPaidEvent {
  export type InputTuple = [
    employee: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    employee: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    employee: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryUpdatedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialPayroll extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialPayroll;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialPayrollInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEmployee: TypedContractMethod<
    [
      employee: AddressLike,
      salaryWei: BigNumberish,
      encSalary: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  employer: TypedContractMethod<[], [string], "view">;

  fundPayroll: TypedContractMethod<[], [void], "payable">;

  getEmployeeInfo: TypedContractMethod<
    [employee: AddressLike],
    [[boolean, bigint] & { active: boolean; lastPaidAt: bigint }],
    "view"
  >;

  getEmployeeList: TypedContractMethod<[], [string[]], "view">;

  getEmployeeSalary: TypedContractMethod<
    [employee: AddressLike],
    [string],
    "view"
  >;

  getMySalary: TypedContractMethod<[], [string], "view">;

  getMyTotalPaid: TypedContractMethod<[], [string], "view">;

  payAll: TypedContractMethod<[], [void], "nonpayable">;

  paySalary: TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;

  removeEmployee: TypedContractMethod<
    [employee: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSalary: TypedContractMethod<
    [
      employee: AddressLike,
      newSalaryWei: BigNumberish,
      encNewSalary: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  withdrawSurplus: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<
    [
      employee: AddressLike,
      salaryWei: BigNumberish,
      encSalary: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "employer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundPayroll"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getEmployeeInfo"
  ): TypedContractMethod<
    [employee: AddressLike],
    [[boolean, bigint] & { active: boolean; lastPaidAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEmployeeList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEmployeeSalary"
  ): TypedContractMethod<[employee: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMySalary"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyTotalPaid"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paySalary"
  ): TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeEmployee"
  ): TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSalary"
  ): TypedContractMethod<
    [
      employee: AddressLike,
      newSalaryWei: BigNumberish,
      encNewSalary: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawSurplus"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EmployeeAdded"
  ): TypedContractEvent<
    EmployeeAddedEvent.InputTuple,
    EmployeeAddedEvent.OutputTuple,
    EmployeeAddedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeRemoved"
  ): TypedContractEvent<
    EmployeeRemovedEvent.InputTuple,
    EmployeeRemovedEvent.OutputTuple,
    EmployeeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollFunded"
  ): TypedContractEvent<
    PayrollFundedEvent.InputTuple,
    PayrollFundedEvent.OutputTuple,
    PayrollFundedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollWithdrawn"
  ): TypedContractEvent<
    PayrollWithdrawnEvent.InputTuple,
    PayrollWithdrawnEvent.OutputTuple,
    PayrollWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "SalaryPaid"
  ): TypedContractEvent<
    SalaryPaidEvent.InputTuple,
    SalaryPaidEvent.OutputTuple,
    SalaryPaidEvent.OutputObject
  >;
  getEvent(
    key: "SalaryUpdated"
  ): TypedContractEvent<
    SalaryUpdatedEvent.InputTuple,
    SalaryUpdatedEvent.OutputTuple,
    SalaryUpdatedEvent.OutputObject
  >;

  filters: {
    "EmployeeAdded(address)": TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;
    EmployeeAdded: TypedContractEvent<
      EmployeeAddedEvent.InputTuple,
      EmployeeAddedEvent.OutputTuple,
      EmployeeAddedEvent.OutputObject
    >;

    "EmployeeRemoved(address)": TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;
    EmployeeRemoved: TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;

    "PayrollFunded(address,uint256)": TypedContractEvent<
      PayrollFundedEvent.InputTuple,
      PayrollFundedEvent.OutputTuple,
      PayrollFundedEvent.OutputObject
    >;
    PayrollFunded: TypedContractEvent<
      PayrollFundedEvent.InputTuple,
      PayrollFundedEvent.OutputTuple,
      PayrollFundedEvent.OutputObject
    >;

    "PayrollWithdrawn(address,uint256)": TypedContractEvent<
      PayrollWithdrawnEvent.InputTuple,
      PayrollWithdrawnEvent.OutputTuple,
      PayrollWithdrawnEvent.OutputObject
    >;
    PayrollWithdrawn: TypedContractEvent<
      PayrollWithdrawnEvent.InputTuple,
      PayrollWithdrawnEvent.OutputTuple,
      PayrollWithdrawnEvent.OutputObject
    >;

    "SalaryPaid(address,uint256,uint256)": TypedContractEvent<
      SalaryPaidEvent.InputTuple,
      SalaryPaidEvent.OutputTuple,
      SalaryPaidEvent.OutputObject
    >;
    SalaryPaid: TypedContractEvent<
      SalaryPaidEvent.InputTuple,
      SalaryPaidEvent.OutputTuple,
      SalaryPaidEvent.OutputObject
    >;

    "SalaryUpdated(address)": TypedContractEvent<
      SalaryUpdatedEvent.InputTuple,
      SalaryUpdatedEvent.OutputTuple,
      SalaryUpdatedEvent.OutputObject
    >;
    SalaryUpdated: TypedContractEvent<
      SalaryUpdatedEvent.InputTuple,
      SalaryUpdatedEvent.OutputTuple,
      SalaryUpdatedEvent.OutputObject
    >;
  };
}
